### ISSUE TITLE
checkout function

### ISSUE THREAD

**Issue by kaaetech** [harveylewis/fuckthupreme-V2#1]
feel free to steal the checkout function from my fork of https://github.com/colincowie/SupremeAutoPurchase or just his one.

**Comment by harveylewis** [comment]
I've got that on the go but thanks anyway, selenium takes a little longer so I'm gonna stick with requests

**Comment by kaaetech** [comment]
yeah you are totally right, i'll follow this project. let me know if you need any help i'm here :D

**Comment by harveylewis** [comment]
Thanks man, just don't go sharing this code everywhere
